# Generated by Django 5.0.7 on 2024-10-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='caterory',
            new_name='category',
        ),
    ]
